import type { Product } from "./types"

export const products: Product[] = [
  // ROKA Products
  {
    id: "1",
    slug: "roka-cp-1x-sunglasses",
    title: "ROKA CP-1X Performance Sunglasses",
    vendor: "roka",
    affiliateUrl: "https://www.roka.com/products/cp-1x?utm_source=longevitybase",
    images: ["/roka-cp-1x-performance-sunglasses-sports-eyewear.jpg"],
    price: 250,
    priceInCents: 25000,
    currency: "USD",
    rating: 4.8,
    category: "wearables",
    goals: ["recovery", "cognitive"],
    tags: ["eyewear", "performance", "sports", "uv-protection"],
    stockStatus: "in_stock",
    short: "Ultra-lightweight performance sunglasses with patented Geko fit system for athletes.",
    pros: ["Won't slip during workouts", "Carl Zeiss lenses", "Made in USA"],
    cons: ["Premium price", "Limited prescription options"],
    createdAt: "2024-01-15",
    popularity: 88,
  },
  {
    id: "2",
    slug: "roka-oslo-sunglasses",
    title: "ROKA Oslo 2.0 Sunglasses",
    vendor: "roka",
    affiliateUrl: "https://www.roka.com/products/oslo?utm_source=longevitybase",
    images: ["/roka-oslo-sunglasses-everyday-wear.jpg"],
    price: 220,
    priceInCents: 22000,
    currency: "USD",
    rating: 4.7,
    category: "wearables",
    goals: ["cognitive", "recovery"],
    tags: ["eyewear", "lifestyle", "uv-protection"],
    stockStatus: "in_stock",
    short: "Stylish everyday sunglasses combining performance technology with modern design.",
    pros: ["Versatile style", "Lightweight", "Excellent optics"],
    cons: ["Not prescription-ready"],
    createdAt: "2024-02-10",
    popularity: 82,
  },

  // Mito Red Light Products
  {
    id: "3",
    slug: "mito-pro-plus-panel",
    title: "MitoPRO+ v2 Red Light Panel",
    vendor: "mito",
    affiliateUrl: "https://mitoredlight.com/products/mitopro-plus?utm_source=longevitybase",
    images: ["/red-light-therapy-panel-professional-device.jpg"],
    price: 849,
    priceInCents: 84900,
    currency: "USD",
    rating: 4.9,
    category: "smart_home",
    goals: ["recovery", "longevity", "sleep"],
    tags: ["red-light-therapy", "recovery", "cellular-health", "anti-aging"],
    stockStatus: "in_stock",
    short: "Professional-grade red light therapy panel for cellular rejuvenation and recovery.",
    pros: ["Medical-grade LEDs", "Full-body coverage", "Clinically proven"],
    cons: ["Large investment", "Requires daily use", "Bulky"],
    createdAt: "2024-01-20",
    popularity: 91,
  },
  {
    id: "4",
    slug: "mito-quad-belt",
    title: "MitoQUAD Wavelength Belt",
    vendor: "mito",
    affiliateUrl: "https://mitoredlight.com/products/mitoquad-belt?utm_source=longevitybase",
    images: ["/red-light-therapy-belt-wearable-device.jpg"],
    price: 599,
    priceInCents: 59900,
    currency: "USD",
    rating: 4.7,
    category: "wearables",
    goals: ["recovery", "longevity"],
    tags: ["red-light-therapy", "wearable", "targeted-recovery"],
    stockStatus: "in_stock",
    short: "Hands-free wearable red light therapy belt for targeted recovery and pain relief.",
    pros: ["Portable", "Hands-free", "Targeted therapy"],
    cons: ["Limited coverage area", "Battery dependent"],
    createdAt: "2024-02-15",
    popularity: 78,
  },
  {
    id: "5",
    slug: "mito-mat",
    title: "MitoMAT Full Body Red Light Mat",
    vendor: "mito",
    affiliateUrl: "https://mitoredlight.com/products/mitomat?utm_source=longevitybase",
    images: ["/red-light-therapy-mat-full-body-yoga.jpg"],
    price: 1299,
    priceInCents: 129900,
    currency: "USD",
    rating: 4.8,
    category: "smart_home",
    goals: ["recovery", "sleep", "longevity"],
    tags: ["red-light-therapy", "full-body", "meditation", "recovery"],
    stockStatus: "in_stock",
    short: "Full-body red light therapy mat perfect for yoga, meditation, and deep recovery.",
    pros: ["Full-body coverage", "Comfortable", "Multi-use"],
    cons: ["Expensive", "Requires storage space"],
    createdAt: "2024-03-01",
    popularity: 85,
  },

  // Dexcom CGM Products
  {
    id: "6",
    slug: "dexcom-g7-cgm",
    title: "Dexcom G7 CGM System",
    vendor: "dexcom",
    affiliateUrl: "https://www.dexcom.com/g7?utm_source=longevitybase",
    images: ["/dexcom-g7-continuous-glucose-monitor-sensor.jpg"],
    price: 399,
    priceInCents: 39900,
    currency: "USD",
    rating: 4.9,
    category: "diagnostics",
    goals: ["metabolic", "longevity"],
    tags: ["cgm", "glucose-monitoring", "metabolic-health", "diabetes"],
    stockStatus: "in_stock",
    short: "Most accurate continuous glucose monitoring system with real-time data and alerts.",
    pros: ["Extremely accurate", "10-day wear", "Real-time alerts", "Small sensor"],
    cons: ["Requires prescription", "Ongoing sensor costs"],
    createdAt: "2024-01-10",
    popularity: 94,
  },
  {
    id: "7",
    slug: "dexcom-stelo",
    title: "Stelo Glucose Biosensor",
    vendor: "dexcom",
    affiliateUrl: "https://www.dexcom.com/stelo?utm_source=longevitybase",
    images: ["/stelo-glucose-biosensor-wearable-device.jpg"],
    price: 299,
    priceInCents: 29900,
    currency: "USD",
    rating: 4.6,
    category: "diagnostics",
    goals: ["metabolic", "longevity"],
    tags: ["glucose-monitoring", "metabolic-health", "no-prescription"],
    stockStatus: "in_stock",
    short: "Over-the-counter glucose biosensor for metabolic insights without prescription.",
    pros: ["No prescription needed", "Easy to use", "Personalized insights"],
    cons: ["Not for diabetes management", "15-day sensors"],
    createdAt: "2024-02-20",
    popularity: 86,
  },

  // TruDiagnostic Products
  {
    id: "8",
    slug: "truage-complete",
    title: "TruAge Complete Collection",
    vendor: "trudiagnostic",
    affiliateUrl: "https://www.trudiagnostic.com/products/truage-complete?utm_source=longevitybase",
    images: ["/trudiagnostic-truage-epigenetic-test-kit.jpg"],
    price: 499,
    priceInCents: 49900,
    currency: "USD",
    rating: 4.8,
    category: "diagnostics",
    goals: ["longevity", "metabolic"],
    tags: ["epigenetic-testing", "biological-age", "dna-methylation", "longevity"],
    stockStatus: "in_stock",
    short: "Comprehensive epigenetic age testing with detailed biological age insights and longevity markers.",
    pros: ["Most comprehensive testing", "Detailed insights", "Actionable recommendations"],
    cons: ["Expensive", "Finger-prick blood sample", "2-3 week turnaround"],
    createdAt: "2024-01-05",
    popularity: 92,
  },
  {
    id: "9",
    slug: "truage-pace",
    title: "TruAge PACE",
    vendor: "trudiagnostic",
    affiliateUrl: "https://www.trudiagnostic.com/products/truage-pace?utm_source=longevitybase",
    images: ["/truage-pace-biological-age-test.jpg"],
    price: 229,
    priceInCents: 22900,
    currency: "USD",
    rating: 4.7,
    category: "diagnostics",
    goals: ["longevity"],
    tags: ["epigenetic-testing", "biological-age", "pace-of-aging"],
    stockStatus: "in_stock",
    short: "Measure your pace of aging with Dunedin PACE epigenetic clock and telomere length.",
    pros: ["Affordable entry point", "Tracks aging rate", "Includes telomeres"],
    cons: ["Less detailed than Complete", "Blood sample required"],
    createdAt: "2024-01-12",
    popularity: 84,
  },

  // Elysium Health Products
  {
    id: "10",
    slug: "elysium-index",
    title: "Elysium Index Biological Age Test",
    vendor: "elysium",
    affiliateUrl: "https://www.elysiumhealth.com/products/index?utm_source=longevitybase",
    images: ["/elysium-index-biological-age-saliva-test-kit.jpg"],
    price: 299,
    priceInCents: 29900,
    currency: "USD",
    rating: 4.7,
    category: "diagnostics",
    goals: ["longevity"],
    tags: ["epigenetic-testing", "biological-age", "saliva-test"],
    stockStatus: "in_stock",
    short: "Saliva-based biological age test measuring 10 different aspects of aging.",
    pros: ["Easy saliva sample", "10 aging metrics", "System age scores", "Developed with Illumina"],
    cons: ["6-week turnaround", "Subscription recommended"],
    createdAt: "2024-02-01",
    popularity: 87,
  },
  {
    id: "11",
    slug: "elysium-basis",
    title: "Elysium Basis NAD+ Supplement",
    vendor: "elysium",
    affiliateUrl: "https://www.elysiumhealth.com/products/basis?utm_source=longevitybase",
    images: ["/elysium-basis-nad-supplement-bottle.jpg"],
    price: 60,
    priceInCents: 6000,
    currency: "USD",
    rating: 4.6,
    category: "nutrition",
    goals: ["longevity", "cognitive"],
    tags: ["nad+", "supplement", "cellular-health", "anti-aging"],
    stockStatus: "in_stock",
    short: "Clinically proven NAD+ booster for cellular health and healthy aging.",
    pros: ["Clinically studied", "Increases NAD+ levels", "Developed by scientists"],
    cons: ["Ongoing monthly cost", "Effects take time"],
    createdAt: "2024-01-25",
    popularity: 89,
  },

  // GlycanAge Products
  {
    id: "12",
    slug: "glycanage-test",
    title: "GlycanAge Biological Age Test",
    vendor: "glycanage",
    affiliateUrl: "https://glycanage.com/products/glycanage-test?utm_source=longevitybase",
    images: ["/glycanage-biological-age-test-kit-blood.jpg"],
    price: 349,
    priceInCents: 34900,
    currency: "USD",
    rating: 4.8,
    category: "diagnostics",
    goals: ["longevity"],
    tags: ["glycan-testing", "biological-age", "inflammation", "immune-health"],
    stockStatus: "in_stock",
    short: "Measure biological age through glycan analysis - the most accurate biomarker of aging.",
    pros: ["Most accurate biomarker", "200+ scientific publications", "Simple finger-prick"],
    cons: ["Not widely known", "Turnaround time"],
    createdAt: "2024-02-05",
    popularity: 81,
  },

  // Theragun Products
  {
    id: "13",
    slug: "theragun-pro",
    title: "Theragun PRO (Gen 6)",
    vendor: "theragun",
    affiliateUrl: "https://www.therabody.com/products/theragun-pro?utm_source=longevitybase",
    images: ["/theragun-pro-massage-gun-professional-device.jpg"],
    price: 599,
    priceInCents: 59900,
    currency: "USD",
    rating: 4.9,
    category: "smart_home",
    goals: ["recovery"],
    tags: ["massage-gun", "percussion-therapy", "muscle-recovery", "professional"],
    stockStatus: "in_stock",
    short: "Professional-grade percussion massage device for deep muscle recovery and pain relief.",
    pros: ["Most powerful", "Quiet operation", "Multiple attachments", "Ergonomic handle"],
    cons: ["Expensive", "Heavy", "Overkill for casual use"],
    createdAt: "2024-01-08",
    popularity: 93,
  },
  {
    id: "14",
    slug: "theragun-prime",
    title: "Theragun Prime (Gen 6)",
    vendor: "theragun",
    affiliateUrl: "https://www.therabody.com/products/theragun-prime?utm_source=longevitybase",
    images: ["/theragun-prime-massage-gun-recovery-device.jpg"],
    price: 299,
    priceInCents: 29900,
    currency: "USD",
    rating: 4.7,
    category: "smart_home",
    goals: ["recovery"],
    tags: ["massage-gun", "percussion-therapy", "muscle-recovery"],
    stockStatus: "in_stock",
    short: "Durable massage gun for reliable recovery with 5 speed settings and impact-resistant design.",
    pros: ["Great value", "Durable", "Simple one-button operation", "Quiet"],
    cons: ["Fewer speeds than PRO", "Shorter battery"],
    createdAt: "2024-01-15",
    popularity: 90,
  },
  {
    id: "15",
    slug: "theragun-relief",
    title: "Theragun Relief",
    vendor: "theragun",
    affiliateUrl: "https://www.therabody.com/products/theragun-relief?utm_source=longevitybase",
    images: ["/theragun-relief-massage-gun-lightweight.jpg"],
    price: 199,
    priceInCents: 19900,
    currency: "USD",
    rating: 4.6,
    category: "smart_home",
    goals: ["recovery"],
    tags: ["massage-gun", "percussion-therapy", "gentle-recovery"],
    stockStatus: "in_stock",
    short: "Lightweight massage gun for fast, effective relief from everyday aches and tension.",
    pros: ["Most affordable", "Lightweight", "Gentle percussion", "Easy to use"],
    cons: ["Less powerful", "Limited to light recovery"],
    createdAt: "2024-02-01",
    popularity: 85,
  },
]
